### ISSUE TITLE
Are there any papers I can refer to?

### ISSUE THREAD

**Issue by nanless** [sandipanadowerah/PhD_SE#1]
Hello,

I am reaching out to inquire if there are any research papers either authored by you or that you might recommend, which pertain to the implementations in this repository, particularly focusing on their performance aspects. I'm looking for additional reading materials to deepen my understanding and to potentially cite in my own research.

Any guidance or suggestions you could provide would be greatly appreciated.

Thank you for your time and consideration.

Best regards,

**Comment by sandipanadowerah** [comment]
Hi,

This work has been published in IEEE SLT 2022, you can cite this paper "Joint
Optimization of Diffusion Probabilistic-Based Multichannel Speech
Enhancement with Far-Field Speaker Verification" following this link
https://ieeexplore.ieee.org/abstract/document/10022350

Regards,
Sandipana

**Comment by nanless** [comment]
Dear Sandipana,

Thank you very much for your response. I truly appreciate you taking the time to assist me.

Best regards,
nanless
